### ISSUE TITLE
TypeError: Cannot read property 'err' of undefined

### ISSUE THREAD

**Issue by YutamaKotaro** [rootzjs/rootzjs-core#10]
I'm sorry to bother you.

![スクリーンショット 2021-02-06 0 46 00](https://user-images.githubusercontent.com/19544218/107055481-b0d02e00-6814-11eb-8bb7-210bd49fff7e.png)

This error occurred when hotReloading, please follow below steps.

1. using  function in 2nd argument of useAction.

```js
node.useAction("NEW_MESSAGE", () => ({ message: 'a' }));
```

2. change something in same file.

The cause of this error is Node has already same keyName ?

**Comment by trishanthnaidu** [comment]
Hi, you are not bothering us at all. 

Thank you for making time in logging this issue. We will add it to our bug stack.

**Comment by trishanthnaidu** [comment]
have solved this issue with the latest v2.2.0 @YutamaKotaro

**Comment by trishanthnaidu** [comment]
closing the issue with the same
