### ISSUE TITLE
Planning typescript ?

### ISSUE THREAD

**Issue by YutamaKotaro** [rootzjs/rootzjs-core#9]
Do you have plan to apply for typescript ?

**Comment by trishanthnaidu** [comment]
Hi YutamaKotaro, 

Yes we are, definitely we have that as a part of our upcoming releases. I have added one issue for typings. But before we proceed with that. 

We are on with making it more Environment specific. This would helps us add additional functionalities to the developer code. 

Thank you for making time to log the issue. It really means a lot for us. We are looking for contributors with Typescript to extend their hands in making this product better. please let me know if any?

Thanks,

**Comment by trishanthnaidu** [comment]
Extended support for typescript as well. The prod and the dev packages has been separated. so better logs for guiding the users where they can go wrong.
